# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-Filter-HTTPHeadersFixup
version:      0.06
version_from: lib/Apache2/Filter/HTTPHeadersFixup.pm
installdirs:  site
requires:
    Apache::Test:                  1.25
    mod_perl:                      2.000001

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
